version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:s2wYBXaYeEdGcae5@db.pnrsjvznrgssigosrqsl.supabase.co:5432/postgres